# Change these first
owner: fredfrazao 
repo: uptime_demo 

sites:
  - name: Authentication Service
    url: https://keycloak.eu1.cloudmobility.io/auth/realms/eu1
  - name: Cloudmobility Charts
    url: https://cloudmobility.github.io/charts/index.yaml
  - name: Eu1z1 Namespaces Cluster
    url: http://apiserver.agile-dingo.cns.eu1.cloudmobility.io/healthz
  - name: CloudMobility Site
    url: https://cloudmobility.io/
  - name: Eu1z1 Namespaces Ingress
    url: https://health.agile-dingo.cns.eu1.cloudmobility.io/
  - name: Image Registry
    url: https://core.harbor.eu1.ext.systems/api/health
  - name: Portal
    url: https://portal.cloudmobility.io/


status-website:
  baseUrl: /uptime_demo
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Cloudmobility
  introTitle: "**Statuspage**"
  introMessage: Cloudmobility StatusPage
  navbar:
    - title: Status
      href: /
