# Change these first
owner: fredfrazao 
repo: uptime_demo 

sites:
  - name: Authentication Service
    url: https://keycloak.eu1.cloudmobility.io/auth/realms/eu1
  - name: Cloudmobility Charts
    url: https://cloudmobility.github.io/charts/index.yaml
  - name: Eu1z1 Namespaces Cluster
    url: http://apiserver.agile-dingo.cns.eu1.cloudmobility.io/healthz
  - name: Eu1z1 Namespaces Ingress
    url: https://health.agile-dingo.cns.eu1.cloudmobility.io/
  - name: Portal
    url: https://portal.cloudmobility.io/


status-website:
  baseUrl: /uptime_demo
  logoUrl: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_QjxrSjO4bK3BKHLiJV0FEGyTYa65D6X5sg&usqp=CAU
  name: Cloudmobility Status page
  introTitle: "**Cloudmobility StatusPage**"
  navbar:
    - title: Status
      href: /uptime_demo/
    - title: cmy-postmortem
      href: https://git.daimler.com/CCP/cmy-postmortem/blob/master/template.md
