# Change these first
owner: fredfrazao 
repo: uptime_demo 

sites:
  - name: Authentication Service
    url: https://keycloak.eu1.cloudmobility.io/auth/realms/eu1
  - name: Cloudmobility Charts
    url: https://cloudmobility.github.io/charts/index.yaml
  - name: Eu1z1 Namespaces Cluster
    url: https://apiserver.agile-dingo.cns.eu1.cloudmobility.io/healthz
  - name: CloudMobility Site
    url: https://cloudmobility.io/
  - name: Eu1z1 Namespaces Ingress
    url: https://health.agile-dingo.cns.eu1.cloudmobility.io/
  - name: Image Registry
    url: https://core.harbor.eu1.ext.systems/api/health
  - name: Portal
    url: https://portal.cloudmobility.io/
  - name: Portal API
    url: portal.cloudmobility.io/api/actuator/health/readiness

status-website:
  baseUrl: /uptime_demo
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime**"
  introMessage: This is a sample status page 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
